#!/usr/bin/bash
data=$(wget -U "Mozilla/5.0" -qO - "http://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=$1&dt=t&q=$(gclip | tr -d '.' | sed "s/[\"'<>]//g")")
echo $data | sed 's/\[\[\[\"//' | cut -d \" -f 1
